### ISSUE TITLE
Erro na URL de recuperação de senha

### ISSUE THREAD

**Issue by newtonbeck** [midianinja/AppNinja#57]
## Passos para reproduzir
- Criar uma conta no app
- Ativar a conta clicando no link recebido por e-mail
- Clicar em "Esqueci minha senha no app"
- Digitar seu e-mail e clicar no botão de recuperar senha
- Clicar no link de recuperar senha recebido por e-mail
- Uma tela de erro aparecerá

## Logs do backend
```
[28/Dec/2018 18:41:28] "POST /api/account/users/send-recover/ HTTP/1.1" 200 0
Internal Server Error: /api/account/users/recover/3/04f8efa12002823e42de78031259f61c9ad0dddf
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/src/app/account/views.py", line 129, in recover_password
    user.password = make_password(data['password'])
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'
[28/Dec/2018 18:41:42] "GET /api/account/users/recover/3/04f8efa12002823e42de78031259f61c9ad0dddf HTTP/1.1" 500 74282
```

## O que deveria acontecer?
Acredito que também precisamos desenvolver uma tela web para isso (precisaremos de mock também)

**Comment by nrbrd** [comment]
Aqui temos que ver como resolver.

Temos pelo menos as seguintes opções:
(1) Desenvolver uma tela web para criação da nova senha
(2) Quando o usuário clicar em "Esqueci a senha", enviar uma senha temporária por email e permitir que ele a troque futuramente pelo app

**Comment by lpirola** [comment]
@aron-bordin a forma mais simples é definir uma senha temporário mas no perfil ele vai ter que poder alterar ou algum outra tela, realmente.
